import {
  segmentTool,
  lineTool,
  rayTool,
  vectorTool,
  segmentGivenLengthTool,
  vectorFromPointTool,
  polarDiameterLineTool,
  polylineTool,
} from './lineHandlers';
import { circleCenterPointTool, compassTool, semicircleTool } from './circleHandlers';
import {
  midpointTool,
  perpendicularTool,
  parallelTool,
  perpendicularBisectorTool,
  angleBisectorTool,
  tangentsTool,
  locusTool,
} from './constructHandlers';
import {
  reflectLineTool,
  reflectPointTool,
  translateVectorTool,
  rotateAroundPointTool,
  dilateFromPointTool,
  reflectAboutCircleTool,
} from './transformHandlers';
import {
  deleteTool,
  showHideObjectTool,
  showHideLabelTool,
  moveGraphicsViewTool,
  selectObjectsTool,
} from './editHandlers';
import {
  pointTool,
  moveTool,
  intersectTool,
  extremumTool,
  rootsTool,
  bestFitLineTool,
  sliderTool,
} from './basicHandlers';
import {
  angleTool,
  angleGivenSizeTool,
  slopeTool,
  distanceTool,
  areaTool,
} from './measureHandlers';
import { textTool, imageTool } from './mediaHandlers';

export const allTools = [
  moveTool,
  pointTool,
  sliderTool,
  intersectTool,
  extremumTool,
  rootsTool,
  bestFitLineTool,
  selectObjectsTool,
  moveGraphicsViewTool,
  deleteTool,
  showHideObjectTool,
  showHideLabelTool,
  segmentTool,
  lineTool,
  rayTool,
  vectorTool,
  segmentGivenLengthTool,
  vectorFromPointTool,
  polarDiameterLineTool,
  polylineTool,
  circleCenterPointTool,
  compassTool,
  semicircleTool,
  midpointTool,
  perpendicularTool,
  perpendicularBisectorTool,
  parallelTool,
  angleBisectorTool,
  tangentsTool,
  locusTool,
  reflectLineTool,
  reflectPointTool,
  translateVectorTool,
  rotateAroundPointTool,
  dilateFromPointTool,
  reflectAboutCircleTool,
  angleTool,
  angleGivenSizeTool,
  slopeTool,
  distanceTool,
  areaTool,
  textTool,
  imageTool,
];
