import {
  segmentTool,
  lineTool,
  rayTool,
  vectorTool,
  segmentGivenLengthTool,
  vectorFromPointTool,
  polarDiameterLineTool,
  polylineTool,
} from './lineHandlers';
import {
  circleCenterPointTool,
  circleCenterRadiusTool,
  circleThreePointsTool,
  compassTool,
  semicircleTool,
  circularArcTool,
  circumcircularArcTool,
  circularSectorTool,
  circumcircularSectorTool,
} from './circleHandlers';
import {
  midpointTool,
  perpendicularTool,
  parallelTool,
  perpendicularBisectorTool,
  angleBisectorTool,
  tangentsTool,
  locusTool,
} from './constructHandlers';
import {
  reflectLineTool,
  reflectPointTool,
  translateVectorTool,
  rotateAroundPointTool,
  dilateFromPointTool,
  reflectAboutCircleTool,
} from './transformHandlers';
import {
  deleteTool,
  showHideObjectTool,
  showHideLabelTool,
  moveGraphicsViewTool,
  selectObjectsTool,
  copyVisualStyleTool,
} from './editHandlers';
import {
  pointTool,
  moveTool,
  intersectTool,
  extremumTool,
  rootsTool,
  bestFitLineTool,
  sliderTool,
} from './basicHandlers';
import {
  pointOnObjectTool,
  attachDetachPointTool,
  complexNumberTool,
  listTool,
} from './pointHandlers';
import {
  polygonTool,
  regularPolygonTool,
  vectorPolygonTool,
  rigidPolygonTool,
} from './polygonHandlers';
import {
  ellipseTool,
  hyperbolaTool,
  parabolaTool,
  conicFivePointsTool,
} from './conicHandlers';
import {
  penTool,
  freehandShapeTool,
  relationTool,
  buttonTool,
  checkBoxTool,
  inputBoxTool,
} from './otherHandlers';
import {
  angleTool,
  angleGivenSizeTool,
  slopeTool,
  distanceTool,
  areaTool,
} from './measureHandlers';
import { textTool, imageTool } from './mediaHandlers';

export const allTools = [
  moveTool,
  pointTool,
  sliderTool,
  intersectTool,
  extremumTool,
  rootsTool,
  bestFitLineTool,
  selectObjectsTool,
  moveGraphicsViewTool,
  copyVisualStyleTool,
  deleteTool,
  showHideObjectTool,
  showHideLabelTool,
  segmentTool,
  lineTool,
  rayTool,
  vectorTool,
  segmentGivenLengthTool,
  vectorFromPointTool,
  polarDiameterLineTool,
  polylineTool,
  circleCenterPointTool,
  circleCenterRadiusTool,
  circleThreePointsTool,
  compassTool,
  semicircleTool,
  circularArcTool,
  circumcircularArcTool,
  circularSectorTool,
  circumcircularSectorTool,
  pointOnObjectTool,
  attachDetachPointTool,
  complexNumberTool,
  listTool,
  polygonTool,
  regularPolygonTool,
  vectorPolygonTool,
  rigidPolygonTool,
  ellipseTool,
  hyperbolaTool,
  parabolaTool,
  conicFivePointsTool,
  penTool,
  freehandShapeTool,
  relationTool,
  buttonTool,
  checkBoxTool,
  inputBoxTool,
  midpointTool,
  perpendicularTool,
  perpendicularBisectorTool,
  parallelTool,
  angleBisectorTool,
  tangentsTool,
  locusTool,
  reflectLineTool,
  reflectPointTool,
  translateVectorTool,
  rotateAroundPointTool,
  dilateFromPointTool,
  reflectAboutCircleTool,
  angleTool,
  angleGivenSizeTool,
  slopeTool,
  distanceTool,
  areaTool,
  textTool,
  imageTool,
];

