import { ToolHandler } from '../ToolManager';
import { ConstructionManager } from '../../construction/ConstructionManager';

export const textTool: ToolHandler = {
  id: 'text',
  clicksRequired: 1,
  commit: (selections: any, cm: ConstructionManager) => {
    const pos = selections[0].value; // Usually a free point generated by ToolManager
    cm.addObject({
      id: `text_${Date.now()}`,
      label: 'Text',
      type: 'text',
      definition: '"Text"',
      dependsOn: [],
      value: { ...pos, text: 'Text' },
      visible: true,
      labelVisible: false,
      style: { color: '#1a1a1a', thickness: 1, opacity: 1 },
      createdByToolId: 'text',
      createdAt: Date.now()
    });
  }
};

export const imageTool: ToolHandler = {
  id: 'image',
  clicksRequired: 1,
  commit: (selections: any, cm: ConstructionManager) => {
    const pos = selections[0].value;
    cm.addObject({
      id: `img_${Date.now()}`,
      label: 'Image',
      type: 'image',
      definition: '',
      dependsOn: [],
      value: { ...pos, src: '', width: 100, height: 100 }, // Stub for MVP
      visible: true,
      labelVisible: false,
      style: { color: '#000', thickness: 1, opacity: 1 },
      createdByToolId: 'image',
      createdAt: Date.now()
    });
  }
};
